version: "3.8"

networks:
  ff-network:

services:
  unleash:
    image: unleashorg/unleash-server
    ports:
      - 4242:4242
    environment:
      DATABASE_URL: postgres://postgres:unleash@db/postgres
    depends_on:
      - db
    command: npm run start
    networks:
      - ff-network

  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks:
      - ff-network
  app:
    image: feature-flag/python:dev
    ports:
      - 5000:5000
    depends_on:
      - unleash
    networks:
      - ff-network
